# Generated by Django 3.2.5 on 2022-09-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserMgt', '0002_paymodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
