# Generated by Django 3.2.5 on 2022-09-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserMgt', '0003_alter_paymodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymodel',
            name='account',
            field=models.PositiveIntegerField(default=123456),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymodel',
            name='bank',
            field=models.CharField(default='eco', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymodel',
            name='card_details',
            field=models.CharField(default='123456', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
