# Generated by Django 3.2.5 on 2022-09-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserMgt', '0004_auto_20220914_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymodel',
            name='account',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymodel',
            name='bank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymodel',
            name='card_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
