# Generated by Django 3.2.5 on 2022-09-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserMgt', '0006_rename_bank_paymodel_bank_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.PositiveIntegerField(blank=True, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=200, null=True)),
                ('card_details', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Refferal',
        ),
    ]
