# Generated by Django 3.2.5 on 2022-08-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoltUser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='profile',
            new_name='userprofile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='has_company',
        ),
        migrations.AddField(
            model_name='profile',
            name='has_company',
            field=models.BooleanField(default=False),
        ),
    ]
