# Generated by Django 3.2.5 on 2022-08-25 10:48

import GoltUser.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoltUser', '0004_alter_ad_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=GoltUser.files.ad_files_directory),
        ),
    ]
