# Generated by Django 3.2.5 on 2022-08-25 10:49

import GoltUser.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoltUser', '0005_alter_ad_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='photo',
            field=models.ImageField(null=True, upload_to=GoltUser.files.ad_files_directory),
        ),
    ]
